package hs_enum

type GameTag int

const (
	TAG_SCRIPT_DATA_NUM_1                           GameTag = 2
	TAG_SCRIPT_DATA_NUM_2                           GameTag = 3
	TAG_SCRIPT_DATA_ENT_1                           GameTag = 4
	TAG_SCRIPT_DATA_ENT_2                           GameTag = 5
	MISSION_EVENT                                   GameTag = 6
	TIMEOUT                                         GameTag = 7
	TURN_START                                      GameTag = 8
	TURN_TIMER_SLUSH                                GameTag = 9
	PREMIUM                                         GameTag = 12
	GOLD_REWARD_STATE                               GameTag = 13
	PLAYSTATE                                       GameTag = 17
	LAST_AFFECTED_BY                                GameTag = 18
	STEP                                            GameTag = 19
	TURN                                            GameTag = 20
	FATIGUE                                         GameTag = 22
	CURRENT_PLAYER                                  GameTag = 23
	FIRST_PLAYER                                    GameTag = 24
	RESOURCES_USED                                  GameTag = 25
	RESOURCES                                       GameTag = 26
	HERO_ENTITY                                     GameTag = 27
	MAXHANDSIZE                                     GameTag = 28
	STARTHANDSIZE                                   GameTag = 29
	PLAYER_ID                                       GameTag = 30
	TEAM_ID                                         GameTag = 31
	TRIGGER_VISUAL                                  GameTag = 32
	RECENTLY_ARRIVED                                GameTag = 33
	PROTECTED                                       GameTag = 34
	PROTECTING                                      GameTag = 35
	DEFENDING                                       GameTag = 36
	PROPOSED_DEFENDER                               GameTag = 37
	ATTACKING                                       GameTag = 38
	PROPOSED_ATTACKER                               GameTag = 39
	ATTACHED                                        GameTag = 40
	EXHAUSTED                                       GameTag = 43
	DAMAGE                                          GameTag = 44
	HEALTH                                          GameTag = 45
	ATK                                             GameTag = 47
	COST                                            GameTag = 48
	ZONE                                            GameTag = 49
	CONTROLLER                                      GameTag = 50
	OWNER                                           GameTag = 51
	DEFINITION                                      GameTag = 52
	ENTITY_ID                                       GameTag = 53
	HISTORY_PROXY                                   GameTag = 54
	ELITE                                           GameTag = 114
	MAXRESOURCES                                    GameTag = 176
	CARD_SET                                        GameTag = 183
	CARDTEXT                                        GameTag = 184
	DURABILITY                                      GameTag = 187
	SILENCED                                        GameTag = 188
	WINDFURY                                        GameTag = 189
	TAUNT                                           GameTag = 190
	STEALTH                                         GameTag = 191
	SPELLPOWER                                      GameTag = 192
	DIVINE_SHIELD                                   GameTag = 194
	CHARGE                                          GameTag = 197
	NEXT_STEP                                       GameTag = 198
	CLASS                                           GameTag = 199
	CARDRACE                                        GameTag = 200
	FACTION                                         GameTag = 201
	CARDTYPE                                        GameTag = 202
	RARITY                                          GameTag = 203
	STATE                                           GameTag = 204
	SUMMONED                                        GameTag = 205
	FREEZE                                          GameTag = 208
	ENRAGED                                         GameTag = 212
	OVERLOAD                                        GameTag = 215
	LOYALTY                                         GameTag = 216
	DEATHRATTLE                                     GameTag = 217
	BATTLECRY                                       GameTag = 218
	SECRET                                          GameTag = 219
	COMBO                                           GameTag = 220
	CANT_HEAL                                       GameTag = 221
	CANT_DAMAGE                                     GameTag = 222
	CANT_SET_ASIDE                                  GameTag = 223
	CANT_REMOVE_FROM_GAME                           GameTag = 224
	CANT_READY                                      GameTag = 225
	CANT_ATTACK                                     GameTag = 227
	CANT_DISCARD                                    GameTag = 230
	CANT_PLAY                                       GameTag = 231
	CANT_DRAW                                       GameTag = 232
	CANT_BE_HEALED                                  GameTag = 239
	IMMUNE                                          GameTag = 240
	CANT_BE_SET_ASIDE                               GameTag = 241
	CANT_BE_REMOVED_FROM_GAME                       GameTag = 242
	CANT_BE_READIED                                 GameTag = 243
	CANT_BE_ATTACKED                                GameTag = 245
	CANT_BE_TARGETED                                GameTag = 246
	CANT_BE_DESTROYED                               GameTag = 247
	CANT_BE_SUMMONING_SICK                          GameTag = 253
	FROZEN                                          GameTag = 260
	JUST_PLAYED                                     GameTag = 261
	LINKED_ENTITY                                   GameTag = 262
	ZONE_POSITION                                   GameTag = 263
	CANT_BE_FROZEN                                  GameTag = 264
	COMBO_ACTIVE                                    GameTag = 266
	CARD_TARGET                                     GameTag = 267
	NUM_CARDS_PLAYED_THIS_TURN                      GameTag = 269
	CANT_BE_TARGETED_BY_OPPONENTS                   GameTag = 270
	NUM_TURNS_IN_PLAY                               GameTag = 271
	NUM_TURNS_LEFT                                  GameTag = 272
	CURRENT_SPELLPOWER                              GameTag = 291
	ARMOR                                           GameTag = 292
	MORPH                                           GameTag = 293
	IS_MORPHED                                      GameTag = 294
	TEMP_RESOURCES                                  GameTag = 295
	OVERLOAD_OWED                                   GameTag = 296
	NUM_ATTACKS_THIS_TURN                           GameTag = 297
	NEXT_ALLY_BUFF                                  GameTag = 302
	MAGNET                                          GameTag = 303
	FIRST_CARD_PLAYED_THIS_TURN                     GameTag = 304
	MULLIGAN_STATE                                  GameTag = 305
	TAUNT_READY                                     GameTag = 306
	STEALTH_READY                                   GameTag = 307
	CHARGE_READY                                    GameTag = 308
	CANT_BE_TARGETED_BY_SPELLS                      GameTag = 311
	SHOULDEXITCOMBAT                                GameTag = 312
	CREATOR                                         GameTag = 313
	CANT_BE_SILENCED                                GameTag = 314
	PARENT_CARD                                     GameTag = 316
	NUM_MINIONS_PLAYED_THIS_TURN                    GameTag = 317
	PREDAMAGE                                       GameTag = 318
	COLLECTIBLE                                     GameTag = 321
	HEALING_DOES_DAMAGE                             GameTag = 326
	DATABASE_ID                                     GameTag = 327
	ENCHANTMENT_BIRTH_VISUAL                        GameTag = 330
	ENCHANTMENT_IDLE_VISUAL                         GameTag = 331
	CANT_BE_TARGETED_BY_HERO_POWERS                 GameTag = 332
	HEALTH_MINIMUM                                  GameTag = 337
	TAG_ONE_TURN_EFFECT                             GameTag = 338
	SILENCE                                         GameTag = 339
	COUNTER                                         GameTag = 340
	ZONES_REVEALED                                  GameTag = 348
	ADJACENT_BUFF                                   GameTag = 350
	FORCED_PLAY                                     GameTag = 352
	LOW_HEALTH_THRESHOLD                            GameTag = 353
	SPELLPOWER_DOUBLE                               GameTag = 356
	SPELL_HEALING_DOUBLE                            GameTag = 357
	NUM_OPTIONS_PLAYED_THIS_TURN                    GameTag = 358
	TO_BE_DESTROYED                                 GameTag = 360
	AURA                                            GameTag = 362
	POISONOUS                                       GameTag = 363
	HERO_POWER_DOUBLE                               GameTag = 366
	AI_MUST_PLAY                                    GameTag = 367
	NUM_MINIONS_PLAYER_KILLED_THIS_TURN             GameTag = 368
	NUM_MINIONS_KILLED_THIS_TURN                    GameTag = 369
	AFFECTED_BY_SPELL_POWER                         GameTag = 370
	EXTRA_MINION_DEATHRATTLES_BASE                  GameTag = 371
	START_WITH_1_HEALTH                             GameTag = 372
	IMMUNE_WHILE_ATTACKING                          GameTag = 373
	MULTIPLY_HERO_DAMAGE                            GameTag = 374
	MULTIPLY_BUFF_VALUE                             GameTag = 375
	CUSTOM_KEYWORD_EFFECT                           GameTag = 376
	TOPDECK                                         GameTag = 377
	CANT_BE_TARGETED_BY_BATTLECRIES                 GameTag = 379
	HERO_POWER                                      GameTag = 380
	DEATHRATTLE_RETURN_ZONE                         GameTag = 382
	STEADY_SHOT_CAN_TARGET                          GameTag = 383
	DISPLAYED_CREATOR                               GameTag = 385
	POWERED_UP                                      GameTag = 386
	SPARE_PART                                      GameTag = 388
	FORGETFUL                                       GameTag = 389
	CAN_SUMMON_MAXPLUSONE_MINION                    GameTag = 390
	OBFUSCATED                                      GameTag = 391
	BURNING                                         GameTag = 392
	OVERLOAD_LOCKED                                 GameTag = 393
	NUM_TIMES_HERO_POWER_USED_THIS_GAME             GameTag = 394
	CURRENT_HEROPOWER_DAMAGE_BONUS                  GameTag = 395
	HEROPOWER_DAMAGE                                GameTag = 396
	LAST_CARD_PLAYED                                GameTag = 397
	NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN        GameTag = 398
	NUM_CARDS_DRAWN_THIS_TURN                       GameTag = 399
	AI_ONE_SHOT_KILL                                GameTag = 400
	EVIL_GLOW                                       GameTag = 401
	HIDE_STATS                                      GameTag = 402
	INSPIRE                                         GameTag = 403
	RECEIVES_DOUBLE_SPELLDAMAGE_BONUS               GameTag = 404
	HEROPOWER_ADDITIONAL_ACTIVATIONS                GameTag = 405
	HEROPOWER_ACTIVATIONS_THIS_TURN                 GameTag = 406
	REVEALED                                        GameTag = 410
	EXTRA_BATTLECRIES_BASE                          GameTag = 411
	NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME        GameTag = 412
	CANNOT_ATTACK_HEROES                            GameTag = 413
	LOCK_AND_LOAD                                   GameTag = 414
	DISCOVER                                        GameTag = 415
	SHADOWFORM                                      GameTag = 416
	NUM_FRIENDLY_MINIONS_THAT_ATTACKED_THIS_TURN    GameTag = 417
	NUM_RESOURCES_SPENT_THIS_GAME                   GameTag = 418
	CHOOSE_BOTH                                     GameTag = 419
	ELECTRIC_CHARGE_LEVEL                           GameTag = 420
	HEAVILY_ARMORED                                 GameTag = 421
	DONT_SHOW_IMMUNE                                GameTag = 422
	RITUAL                                          GameTag = 424
	PREHEALING                                      GameTag = 425
	APPEAR_FUNCTIONALLY_DEAD                        GameTag = 426
	OVERLOAD_THIS_GAME                              GameTag = 427
	SPELLS_COST_HEALTH                              GameTag = 431
	HISTORY_PROXY_NO_BIG_CARD                       GameTag = 432
	PROXY_CTHUN                                     GameTag = 434
	TRANSFORMED_FROM_CARD                           GameTag = 435
	CTHUN                                           GameTag = 436
	CAST_RANDOM_SPELLS                              GameTag = 437
	SHIFTING                                        GameTag = 438
	JADE_GOLEM                                      GameTag = 441
	EMBRACE_THE_SHADOW                              GameTag = 442
	CHOOSE_ONE                                      GameTag = 443
	EXTRA_ATTACKS_THIS_TURN                         GameTag = 444
	SEEN_CTHUN                                      GameTag = 445
	MINION_TYPE_REFERENCE                           GameTag = 447
	UNTOUCHABLE                                     GameTag = 448
	RED_MANA_CRYSTALS                               GameTag = 449
	SCORE_LABELID_1                                 GameTag = 450
	SCORE_VALUE_1                                   GameTag = 451
	SCORE_LABELID_2                                 GameTag = 452
	SCORE_LABELID_3                                 GameTag = 454
	SCORE_VALUE_2                                   GameTag = 453
	SCORE_VALUE_3                                   GameTag = 455
	CANT_BE_FATIGUED                                GameTag = 456
	AUTOATTACK                                      GameTag = 457
	ARMS_DEALING                                    GameTag = 458
	QUEST                                           GameTag = 462
	TAG_LAST_KNOWN_COST_IN_HAND                     GameTag = 466
	DEFINING_ENCHANTMENT                            GameTag = 469
	FINISH_ATTACK_SPELL_ON_DAMAGE                   GameTag = 470
	MODULAR_ENTITY_PART_1                           GameTag = 471
	MODULAR_ENTITY_PART_2                           GameTag = 472
	MODIFY_DEFINITION_ATTACK                        GameTag = 473
	MODIFY_DEFINITION_HEALTH                        GameTag = 474
	MODIFY_DEFINITION_COST                          GameTag = 475
	MULTIPLE_CLASSES                                GameTag = 476
	ALL_TARGETS_RANDOM                              GameTag = 477
	MULTI_CLASS_GROUP                               GameTag = 480
	CARD_COSTS_HEALTH                               GameTag = 481
	GRIMY_GOONS                                     GameTag = 482
	JADE_LOTUS                                      GameTag = 483
	KABAL                                           GameTag = 484
	ADDITIONAL_PLAY_REQS_1                          GameTag = 515
	ADDITIONAL_PLAY_REQS_2                          GameTag = 516
	ELEMENTAL_POWERED_UP                            GameTag = 532
	QUEST_PROGRESS                                  GameTag = 534
	QUEST_PROGRESS_TOTAL                            GameTag = 535
	QUEST_CONTRIBUTOR                               GameTag = 541
	ADAPT                                           GameTag = 546
	IS_CURRENT_TURN_AN_EXTRA_TURN                   GameTag = 547
	EXTRA_TURNS_TAKEN_THIS_GAME                     GameTag = 548
	TREASURE                                        GameTag = 557
	TREASURE_DEFINTIONAL_ATTACK                     GameTag = 558
	TREASURE_DEFINTIONAL_COST                       GameTag = 559
	TREASURE_DEFINTIONAL_HEALTH                     GameTag = 560
	ACTS_LIKE_A_SPELL                               GameTag = 561
	SHIFTING_MINION                                 GameTag = 549
	SHIFTING_WEAPON                                 GameTag = 550
	DEATH_KNIGHT                                    GameTag = 554
	BOSS                                            GameTag = 556
	STAMPEDE                                        GameTag = 564
	EMPOWERED_TREASURE                              GameTag = 646
	ONE_SIDED_GHOSTLY                               GameTag = 648
	CURRENT_NEGATIVE_SPELLPOWER                     GameTag = 651
	IS_VAMPIRE                                      GameTag = 680
	CORRUPTED                                       GameTag = 681
	HIDE_HEALTH                                     GameTag = 682
	HIDE_ATTACK                                     GameTag = 683
	HIDE_COST                                       GameTag = 684
	LIFESTEAL                                       GameTag = 685
	OVERRIDE_EMOTE_0                                GameTag = 740
	OVERRIDE_EMOTE_1                                GameTag = 741
	OVERRIDE_EMOTE_2                                GameTag = 742
	OVERRIDE_EMOTE_3                                GameTag = 743
	OVERRIDE_EMOTE_4                                GameTag = 744
	OVERRIDE_EMOTE_5                                GameTag = 745
	SCORE_FOOTERID                                  GameTag = 751
	RECRUIT                                         GameTag = 763
	LOOT_CARD_1                                     GameTag = 764
	LOOT_CARD_2                                     GameTag = 765
	LOOT_CARD_3                                     GameTag = 766
	HERO_POWER_DISABLED                             GameTag = 777
	VALEERASHADOW                                   GameTag = 779
	OVERRIDECARDNAME                                GameTag = 781
	OVERRIDECARDTEXTBUILDER                         GameTag = 782
	DUNGEON_PASSIVE_BUFF                            GameTag = 783
	GHOSTLY                                         GameTag = 785
	DISGUISED_TWIN                                  GameTag = 788
	SECRET_DEATHRATTLE                              GameTag = 789
	RUSH                                            GameTag = 791
	REVEAL_CHOICES                                  GameTag = 792
	HERO_DECK_ID                                    GameTag = 793
	HIDDEN_CHOICE                                   GameTag = 813
	ZOMBEAST                                        GameTag = 823
	HERO_EMOTE_SILENCED                             GameTag = 832
	MINION_IN_HAND_BUFF                             GameTag = 845
	ECHO                                            GameTag = 846
	MODULAR                                         GameTag = 849
	IGNORE_HIDE_STATS_FOR_BIG_CARD                  GameTag = 857
	REAL_TIME_TRANSFORM                             GameTag = 859
	WAIT_FOR_PLAYER_RECONNECT_PERIOD                GameTag = 860
	ETHEREAL                                        GameTag = 880
	EXTRA_DEATHRATTLES_BASE                         GameTag = 882
	PHASED_RESTART                                  GameTag = 888
	HEALTH_DISPLAY                                  GameTag = 917
	ENABLE_HEALTH_DISPLAY                           GameTag = 920
	VOODOO_LINK                                     GameTag = 921
	OVERKILL                                        GameTag = 923
	PROPHECY                                        GameTag = 924
	ATTACKABLE_BY_RUSH                              GameTag = 930
	SHIFTING_SPELL                                  GameTag = 936
	USE_ALTERNATE_CARD_TEXT                         GameTag = 955
	SUPPRESS_DEATH_SOUND                            GameTag = 959
	ECHOING_OOZE_SPELL                              GameTag = 963
	COLLECTIONMANAGER_FILTER_MANA_EVEN              GameTag = 956
	COLLECTIONMANAGER_FILTER_MANA_ODD               GameTag = 957
	AMOUNT_HEALED_THIS_GAME                         GameTag = 958
	ZOMBEAST_DEBUG_CURRENT_BEAST_DATABASE_ID        GameTag = 964
	ZOMBEAST_DEBUG_CURRENT_ITERATION                GameTag = 965
	ZOMBEAST_DEBUG_MAX_ITERATIONS                   GameTag = 966
	START_OF_GAME                                   GameTag = 968
	ENCHANTMENT_INVISIBLE                           GameTag = 976
	PUZZLE                                          GameTag = 979
	PUZZLE_PROGRESS                                 GameTag = 980
	PUZZLE_PROGRESS_TOTAL                           GameTag = 981
	PUZZLE_TYPE                                     GameTag = 982
	PUZZLE_COMPLETED                                GameTag = 984
	CONCEDE_BUTTON_ALTERNATIVE_TEXT                 GameTag = 985
	HIDE_RESTART_BUTTON                             GameTag = 990
	WILD                                            GameTag = 991
	HALL_OF_FAME                                    GameTag = 992
	MARK_OF_EVIL                                    GameTag = 994
	DECK_RULE_MOD_DECK_SIZE                         GameTag = 997
	FAST_BATTLECRY                                  GameTag = 998
	END_TURN_BUTTON_ALTERNATIVE_APPEARANCE          GameTag = 1000
	WEATHER                                         GameTag = 1002
	WEATHERSNOWSTORM                                GameTag = 1012
	WEATHERTHUNDERSTORM                             GameTag = 1013
	WEATHERFIRESTORM                                GameTag = 1014
	WAND                                            GameTag = 1015
	TREAT_AS_PLAYED_HERO_CARD                       GameTag = 1016
	NUM_HERO_POWER_DAMAGE_THIS_GAME                 GameTag = 1025
	PUZZLE_NAME                                     GameTag = 1026
	TURN_INDICATOR_ALTERNATIVE_APPEARANCE           GameTag = 1027
	PREVIOUS_PUZZLE_COMPLETED                       GameTag = 1042
	GLORIOUSGLOOP                                   GameTag = 1044
	HEALTH_DISPLAY_COLOR                            GameTag = 1046
	HEALTH_DISPLAY_NEGATIVE                         GameTag = 1047
	WHIZBANG_DECK_ID                                GameTag = 1048
	HIDE_OUT_OF_CARDS_WARNING                       GameTag = 1050
	GEARS                                           GameTag = 1052
	LUNAHIGHLIGHTHINT                               GameTag = 1054
	SUPPRESS_JOBS_DONE_VO                           GameTag = 1055
	SHRINE                                          GameTag = 1057
	ALL_HEALING_DOUBLE                              GameTag = 1058
	BLOCK_ALL_INPUT                                 GameTag = 1071
	PUZZLE_MODE                                     GameTag = 1073
	CARD_DOES_NOTHING                               GameTag = 1075
	CASTSWHENDRAWN                                  GameTag = 1077
	SQUELCH_NON_GAME_TRIGGERS_AND_MODIFIERS         GameTag = 1087
	QUEST_REWARD_DATABASE_ID                        GameTag = 1089
	DORMANT                                         GameTag = 1090
	CUSTOMTEXT1                                     GameTag = 1093
	CUSTOMTEXT2                                     GameTag = 1094
	CUSTOMTEXT3                                     GameTag = 1095
	FLOOPY                                          GameTag = 1097
	PLAYER_BASE_SHRINE_DECK_ID                      GameTag = 1099
	HIDE_WATERMARK                                  GameTag = 1107
	EXTRA_MINION_BATTLECRIES_BASE                   GameTag = 1112
	RUN_PROGRESS                                    GameTag = 1113
	NON_KEYWORD_ECHO                                GameTag = 1114
	PLAYER_TAG_THRESHOLD_TAG_ID                     GameTag = 1115
	PLAYER_TAG_THRESHOLD_VALUE                      GameTag = 1116
	HEALING_DOES_DAMAGE_HINT                        GameTag = 1117
	AFFECTED_BY_HEALING_DOES_DAMAGE                 GameTag = 1118
	DECK_LIST_SORT_ORDER                            GameTag = 1125
	EXTRA_BATTLECRIES_ADDITIONAL                    GameTag = 1126
	EXTRA_DEATHRATTLES_ADDITIONAL                   GameTag = 1131
	ALTERNATE_MOUSE_OVER_CARD                       GameTag = 1132
	ENCHANTMENT_BANNER_TEXT                         GameTag = 1135
	EXTRA_SPELL_CASTS_BASE                          GameTag = 1140
	MOUSE_OVER_CARD_APPEARANCE                      GameTag = 1142
	IS_ADVENTURE_SCENARIO                           GameTag = 1172
	TWINSPELL_COPY                                  GameTag = 1186
	TWINSPELL                                       GameTag = 1193
	COIN_MANA_GEM                                   GameTag = 1199
	MEGA_WINDFURY                                   GameTag = 1207
	TWINSPELLPENDING                                GameTag = 1269
	EXTRA_OVERLOAD_SPELL_CASTS_BASE                 GameTag = 1272
	DRUSTVAR_HORROR_DEBUG_CURRENT_SPELL_DATABASE_ID GameTag = 1280
	DRUSTVAR_HORROR_DEBUG_CURRENT_ITERATION         GameTag = 1281
	HEROIC_HERO_POWER                               GameTag = 1282
	DRUSTVAR_HORROR_DEBUG_MAX_ITERATIONS            GameTag = 1283
	CREATOR_DBID                                    GameTag = 1284
	FATIGUEREFERENCE                                GameTag = 1290
	HERO_FLYING                                     GameTag = 1293
	UI_BUFF_HEALTH_UP                               GameTag = 1294
	UI_BUFF_SET_COST_ZERO                           GameTag = 1295
	UI_BUFF_COST_DOWN                               GameTag = 1296
	UI_BUFF_ATK_UP                                  GameTag = 1297
	UI_BUFF_COST_UP                                 GameTag = 1298
	DEBUG_DISPLAY_TAG_BOTTOM_RIGHT                  GameTag = 1313
	DEBUG_DISPLAY_TAG_TOP_RIGHT                     GameTag = 1314
	COPIED_BY_KHADGAR                               GameTag = 1326
	ALTERNATE_CHAPTER_VO                            GameTag = 1334
	EXTRA_SPELL_CASTS_ADDITIONAL                    GameTag = 1348
	SQUELCH_LIFETIME_EFFECTS                        GameTag = 1350

	INVISIBLE_DEATHRATTLE GameTag = 335
	IMMUNE_TO_SPELLPOWER  GameTag = 349
	ATTACK_VISUAL_TYPE    GameTag = 251
	DEV_STATE             GameTag = 268
	GRANT_CHARGE          GameTag = 355
	HEAL_TARGED          GameTag = 361

	// strings (all deleted?)
	CARDTEXT_INHAND      GameTag = CARDTEXT // But it came back...
	CARDNAME             GameTag = 185
	ARTISTNAME           GameTag = 342
	FLAVORTEXT           GameTag = 351
	HOW_TO_EARN          GameTag = 364
	HOW_TO_EARN_GOLDEN   GameTag = 365
	CARD_TEXT_IN_PLAY    GameTag = 252
	TARGETING_ARROW_TEXT GameTag = 325
	LOCALIZATION_NOTES  GameTag = 344

	//Renamed
	CANT_BE_DAMAGED                GameTag = IMMUNE
	CANT_BE_DISPELLED              GameTag = CANT_BE_SILENCED
	CANT_BE_TARGETED_BY_ABILITIES  GameTag = CANT_BE_TARGETED_BY_SPELLS
	DEATH_RATTLE                   GameTag = DEATHRATTLE
	DEATHRATTLE_SENDS_BACK_TO_DECK GameTag = DEATHRATTLE_RETURN_ZONE
	EXTRA_DEATHRATTLES             GameTag = EXTRA_MINION_DEATHRATTLES_BASE
	HAND_REVEALED                  GameTag = ZONES_REVEALED
	HEALING_DOUBLE                 GameTag = SPELL_HEALING_DOUBLE
	// HIDE_COST GameTag = HIDE_STATS  # Added back
	KAZAKUS_POTION_POWER_1 GameTag = MODULAR_ENTITY_PART_1
	KAZAKUS_POTION_POWER_2 GameTag = MODULAR_ENTITY_PART_2
	LINKEDCARD             GameTag = LINKED_ENTITY
	RECALL                 GameTag = OVERLOAD
	RECALL_OWED            GameTag = OVERLOAD_OWED
	TAG_HERO_POWER_DOUBLE  GameTag = HERO_POWER_DOUBLE
	TAG_AI_MUST_PLAY       GameTag = AI_MUST_PLAY
	// TREASURE GameTag = DISCOVER  # Added back
	SHOWN_HERO_POWER GameTag = HERO_POWER
	EVILZUG          GameTag = MARK_OF_EVIL

	// Deleted
	IGNORE_DAMAGE                      GameTag = 1
	COPY_DEATHRATTLE                   GameTag = 55
	COPY_DEATHRATTLE_INDEX             GameTag = 56
	CARD_ID                            GameTag = 186
	INCOMING_HEALING_MULTIPLIER        GameTag = 233
	INCOMING_HEALING_ADJUSTMENT        GameTag = 234
	INCOMING_HEALING_CAP               GameTag = 235
	INCOMING_DAMAGE_MULTIPLIER         GameTag = 236
	INCOMING_DAMAGE_ADJUSTMENT         GameTag = 237
	INCOMING_DAMAGE_CAP                GameTag = 238
	OUTGOING_DAMAGE_CAP                GameTag = 273
	OUTGOING_DAMAGE_ADJUSTMENT         GameTag = 274
	OUTGOING_DAMAGE_MULTIPLIER         GameTag = 275
	OUTGOING_HEALING_CAP               GameTag = 276
	OUTGOING_HEALING_ADJUSTMENT        GameTag = 277
	OUTGOING_HEALING_MULTIPLIER        GameTag = 278
	INCOMING_ABILITY_DAMAGE_ADJUSTMENT GameTag = 279
	INCOMING_COMBAT_DAMAGE_ADJUSTMENT  GameTag = 280
	OUTGOING_ABILITY_DAMAGE_ADJUSTMENT GameTag = 281
	OUTGOING_COMBAT_DAMAGE_ADJUSTMENT  GameTag = 282
	OUTGOING_ABILITY_DAMAGE_MULTIPLIER GameTag = 283
	OUTGOING_ABILITY_DAMAGE_CAP        GameTag = 284
	INCOMING_ABILITY_DAMAGE_MULTIPLIER GameTag = 285
	INCOMING_ABILITY_DAMAGE_CAP        GameTag = 286
	OUTGOING_COMBAT_DAMAGE_MULTIPLIER  GameTag = 287
	OUTGOING_COMBAT_DAMAGE_CAP         GameTag = 288
	INCOMING_COMBAT_DAMAGE_MULTIPLIER  GameTag = 289
	INCOMING_COMBAT_DAMAGE_CAP         GameTag = 290
	DIVINE_SHIELD_READY                GameTag = 314
	IGNORE_DAMAGE_OFF                  GameTag = 354
	NUM_OPTIONS                        GameTag = 359
	PENDING_EVOLUTIONS                 GameTag = 461

	// Missing/guessed, only present in logs
	WEAPON        GameTag = 334
	DISCARD_CARDS GameTag = 890
	CANT_BE_EXHAUSTED GameTag = 244
	CANT_EXHAUST      GameTag = 226
	CANT_TARGET       GameTag = 228
	CANT_DESTROY      GameTag = 229
)

var (
	gameTagNames = []string{}
)

func init() {
	gameTagNames[32] = "TriggerVisual"
	gameTagNames[45] = "Health"
	gameTagNames[47] = "Atk"
	gameTagNames[48] = "Cost"
	gameTagNames[114] = "Elite"
	gameTagNames[183] = "CardSet"
	gameTagNames[184] = "CardTextInHand"
	gameTagNames[185] = "CardName"
	gameTagNames[187] = "Durability"
	gameTagNames[189] = "Windfury"
	gameTagNames[190] = "Taunt"
	gameTagNames[191] = "Stealth"
	gameTagNames[192] = "Spellpower"
	gameTagNames[194] = "Divine Shield"
	gameTagNames[197] = "Charge"
	gameTagNames[199] = "Class"
	gameTagNames[200] = "Race"
	gameTagNames[201] = "Faction"
	gameTagNames[203] = "Rarity"
	gameTagNames[202] = "CardType"
	gameTagNames[208] = "Freeze"
	gameTagNames[212] = "Enrage"
	gameTagNames[215] = "Recall"
	gameTagNames[217] = "Deathrattle"
	gameTagNames[218] = "Battlecry"
	gameTagNames[219] = "Secret"
	gameTagNames[220] = "Combo"
	gameTagNames[240] = "Cant Be Damaged"
	gameTagNames[251] = "AttackVisualType"
	gameTagNames[252] = "CardTextInPlay"
	gameTagNames[268] = "DevState"
	gameTagNames[293] = "Morph"
	gameTagNames[321] = "Collectible"
	gameTagNames[325] = "TargetingArrowText"
	gameTagNames[330] = "EnchantmentBirthVisual"
	gameTagNames[331] = "EnchantmentIdleVisual"
	gameTagNames[335] = "InvisibleDeathrattle"
	gameTagNames[338] = "OneTurnEffect"
	gameTagNames[339] = "Silence"
	gameTagNames[340] = "Counter"
	gameTagNames[342] = "ArtistName"
	gameTagNames[349] = "ImmuneToSpellpower"
	gameTagNames[350] = "AdjacentBuff"
	gameTagNames[351] = "FlavorText"
	gameTagNames[361] = "HealTarget"
	gameTagNames[362] = "Aura"
	gameTagNames[363] = "Poisonous"
	gameTagNames[364] = "HowToGetThisCard"
	gameTagNames[365] = "HowToGetThisGoldCard"
	gameTagNames[367] = "AIMustPlay"
	gameTagNames[370] = "AffectedBySpellPower"
	gameTagNames[388] = "SparePart"
	gameTagNames[402] = "HideStats"
	gameTagNames[415] = "Treasure"
	gameTagNames[457] = "AutoAttack"

}

func (g GameTag) String() string {

	return gameTagNames[g]

}
